package in.postkaro.enums;

public enum BusinessCategory {
	FOOD_BEVERAGE, FASHION_BEAUTY, FITNESS_WELLNESS, EDUCATION_COACHING, REAL_ESTATE, TECHNOLOGY_SAAS,
	TRAVEL_HOSPITALITY, PERSONAL_BRAND, OTHER
}